/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_cojac_models_ConversionBehaviour */

#ifndef _Included_com_github_cojac_models_ConversionBehaviour
#define _Included_com_github_cojac_models_ConversionBehaviour
#ifdef __cplusplus
extern "C" {
#endif
#undef com_github_cojac_models_ConversionBehaviour_FE_UPWARD
#define com_github_cojac_models_ConversionBehaviour_FE_UPWARD 2048L
#undef com_github_cojac_models_ConversionBehaviour_FE_TONEAREST
#define com_github_cojac_models_ConversionBehaviour_FE_TONEAREST 0L
#undef com_github_cojac_models_ConversionBehaviour_FE_TOWARDZERO
#define com_github_cojac_models_ConversionBehaviour_FE_TOWARDZERO 3072L
#undef com_github_cojac_models_ConversionBehaviour_FE_DOWNWARD
#define com_github_cojac_models_ConversionBehaviour_FE_DOWNWARD 1024L
#undef com_github_cojac_models_ConversionBehaviour_SIGNIFICATIVE_DOUBLE_BITS
#define com_github_cojac_models_ConversionBehaviour_SIGNIFICATIVE_DOUBLE_BITS 52L
#undef com_github_cojac_models_ConversionBehaviour_SIGNIFICATIVE_FLOAT_BITS
#define com_github_cojac_models_ConversionBehaviour_SIGNIFICATIVE_FLOAT_BITS 23L
/*
 * Class:     com_github_cojac_models_ConversionBehaviour
 * Method:    changeRounding
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_github_cojac_models_ConversionBehaviour_changeRounding
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
